### ISSUE TITLE
support comment system to your blog

### ISSUE THREAD

**Issue by tak-bro** [KimBoWoon/KimBoWoon.github.io#1]
블로그 글 잘보고 있습니다. 
너의 블로그에 disqus 기능([참고](https://github.com/KimBoWoon/KimBoWoon.github.io/blob/master/README.en.md#comment-support))을 달면 더 좋을거 같아요.
열심히해서 보기 좋습니다

**Comment by KimBoWoon** [comment]
조언 감사합니다!
헛다리를 짚어서 몇 번 실수를 했지만 결국에는 적용 시켰습니다.
한동안 포스트가 없었는데 앞으로 조금씩 신경쓰도록 하겠습니다.
그리고 이슈는 닫을게요
